# Chapter 01 - Vectors, Matrices, and Arrays

## Creating a Vector

In [12]:
# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1,2,3])

# Create a vector as a column
vector_column = np.array([[1],[2],[3]])

print("row vector: " + str(vector_row))
print("shape: " + str(vector_row.shape))
print("column vector: " + str(vector_column))
print("shape: " + str(vector_column.shape))

row vector: [1 2 3]
shape: (3,)
column vector: [[1]
 [2]
 [3]]
shape: (3, 1)


## Creating a Matrix

In [11]:
# Load library
import numpy as np

# Create a matrix
matrix = np.array([[1,2],[1,2],[1,2]])
print(matrix)
print(matrix.shape)

[[1 2]
 [1 2]
 [1 2]]
(3, 2)


## Creating a Sparse Matrix

In [2]:
# Load libraries
import numpy as np
from scipy import sparse

# Create a matrix
matrix = np.array([[0,0],
                  [0,1],
                  [3,0]])

# Create compressed sparse row matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


## Selecting Elements

In [4]:
# Load library
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Select third element of vector
print(vector[2])

# Select second row, second column
print(matrix[1, 1])

# Select the first two rows and all columns of a matrix
print(matrix[:2,:])

# Select all rows, and the second column
print(matrix[:,1:2])

3
5
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


## Describing a Matrix

In [11]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# View number of rows and columns
print(matrix.shape)

# View number of elements (rows * columns)
print(matrix.size)

# View number of dimensions
print(matrix.ndim)

(3, 3)
9
2


## Applying Operations to Elements

In [13]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [16]:
# Create funtion that adds 100 to something
add_100 = lambda i : i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
print(vectorized_add_100(matrix))

[[101 102 103]
 [104 105 106]
 [107 108 109]]


## Finding the Max and Min Values

In [17]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [20]:
print(np.max(matrix))
print(np.min(matrix))

# Find max element in each column
print(np.max(matrix, axis=0))

# Find max element in each row
print(np.max(matrix, axis=1))

9
1
[7 8 9]
[3 6 9]


## Calculating the Average, Variance, and Standard Deviation

In [24]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 6, 6],
                  [7, 8, 9]])

In [25]:
print(np.mean(matrix))
print(np.var(matrix))
print(np.std(matrix))

# Find the mean value in each column
print(np.mean(matrix, axis=0))

5.111111111111111
6.765432098765432
2.601044424604361
[4.         5.33333333 6.        ]


## Reshaping Arrays

In [26]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 6, 6],
                  [7, 8, 9],
                  [10,11,12]])

In [30]:
print(matrix.reshape(2, 6))
# -1 means as many as needed
print(matrix.reshape(3, -1))

[[ 1  2  3  4  6  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 6  6  7  8]
 [ 9 10 11 12]]


## Transposing a Vector or Matrix

In [31]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 6, 6],
                  [7, 8, 9]])

In [33]:
print(matrix.T)

# Transpose a row vector
print(np.array([[1,2,3,4]]).T)

[[1 4 7]
 [2 6 8]
 [3 6 9]]
[[1]
 [2]
 [3]
 [4]]


## Flattening a Matrix

In [34]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 6, 6],
                  [7, 8, 9]])

In [36]:
print(matrix.flatten())

# alternatively
print(matrix.reshape(1,-1))

[1 2 3 4 6 6 7 8 9]
[[1 2 3 4 6 6 7 8 9]]


## Finding the Rank of a Matrix

In [38]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 1, 1],
                  [1, 1, 10],
                  [1, 1, 15]])

In [39]:
print(np.linalg.matrix_rank(matrix))

2


## Calculating the Determinant

In [40]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                  [2, 4, 6],
                  [3, 8, 9]])

In [41]:
print(np.linalg.det(matrix))

0.0


## Getting the Diagonal of a Matrix

In [42]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                  [2, 4, 6],
                  [3, 8, 9]])

In [44]:
print(matrix.diagonal())

# Return diagonal one above the main diagonal
print(matrix.diagonal(offset=1))

# Return diagonal one below the main diagonal
print(matrix.diagonal(offset=-1))

[1 4 9]
[2 6]
[2 8]


## Calculating the Trace of a Matrix

In [45]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                  [2, 4, 6],
                  [3, 8, 9]])

In [46]:
print(matrix.trace())

14


## Finding Eigenvalues and Eigenvectors

In [47]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, -1, 3],
                  [1, 1, 6],
                  [3, 8, 9]])

In [48]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


## Calculating Dot Products

In [49]:
# Load library
import numpy as np

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

print(np.dot(vector_a, vector_b))

32


## Adding and Subtracting Matrices

In [50]:
# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1, 1],
                  [1, 1, 1],
                  [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                  [1, 3, 1],
                  [1, 3, 8]])

In [52]:
print(np.add(matrix_a,matrix_b))
print(np.subtract(matrix_a,matrix_b))

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


## Multiplying Matrices

In [54]:
# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1],
                  [1, 2]])

# Create matrix
matrix_b = np.array([[1, 3],
                  [1, 2]])

print(np.dot(matrix_a,matrix_b))

# Multiply two matrices element-wise
print(matrix_a * matrix_b)

[[2 5]
 [3 7]]
[[1 3]
 [1 4]]


## Inverting a Matrix

In [55]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 1],
                  [2, 5]])

# Calculate inverse of matrix
print(np.linalg.inv(matrix))

[[ 1.66666667 -0.33333333]
 [-0.66666667  0.33333333]]


## Generating Random Values

In [57]:
# Load library
import numpy as np

# Set seed
np.random.seed(0)

# Generate three random values between 0.0 and 1.0
print(np.random.random(3))

# Generate three random integers between 1 and 10
print(np.random.randint(0, 11, 3))

[0.5488135  0.71518937 0.60276338]
[3 7 9]


In [58]:
# Draw three numbers from a normal distribution with mean 0.0 and standard deviation of 1.0
print(np.random.normal(0.0, 1.0 ,3))

# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
print(np.random.logistic(0.0, 1.0, 3))

# Draw three numbers greater than or equal to 1.0 and less than 2.0
print(np.random.uniform(1.0, 2.0, 3))

[-1.42232584  1.52006949 -0.29139398]
[-0.98118713 -0.08939902  1.46416405]
[1.47997717 1.3927848  1.83607876]
